version: "3.7"

services:
  db_address:
    container_name: mssqlDbAddress
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    volumes:
      - example_volume:/var/opt/mssql/address
    environment:
      SA_PASSWORD: "pw123_Example"
      ACCEPT_EULA: "Y"
    ports:
      - "1433"
      - "1401:1433"
    networks:
      - example
    restart: on-failure

  db_person:
    container_name: mssqlDbPerson
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    volumes:
      - example_volume:/var/opt/mssql/person
    environment:
      SA_PASSWORD: "pw123_Example"
      ACCEPT_EULA: "Y"
    ports:
      - "1433"
      - "1402:1433"
    networks:
      - example
    restart: on-failure

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - example
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - example
    healthcheck:
      test: ["CMD", "java", "-jar", "/Ping.jar", "localhost", "9092"]
      interval: 30s
      timeout: 10s
      retries: 4

  # kafka-setup:
  #   image: confluentinc/cp-kafka:latest
  #   hostname: kafka-setup
  #   container_name: kafka-setup
  #   depends_on:
  #     - kafka
  #   volumes:
  #     - $PWD/connectors:/tmp/connectors
  #     - $PWD/dashboard:/tmp/dashboard
  #   command: "bash -c 'echo Waiting for Kafka to be ready... && \
  #                      cub kafka-ready -b kafka:9092 1 20 && \
  #                      kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic CreateAddress && \
  #                      kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic DeleteAddress '"
  #   environment:
  #     # The following settings are listed here only to satisfy the image's requirements.
  #     # We override the image's `command` anyways, hence this container will not start a broker.
  #     KAFKA_BROKER_ID: ignored
  #     KAFKA_ZOOKEEPER_CONNECT: ignored
  #   restart: on-failure
  #   networks:
  #     - example
  
  backend_address:
    restart: on-failure
    depends_on:
      - db_address
      - kafka
      # - kafka-setup
    container_name: backendAPIAddress
    build:
      context: backend\ExampleAPI
      dockerfile: ExampleAPI\Dockerfile
    ports:
      - "7176:80"
    networks:
      - example

  backend_person:
    restart: on-failure
    depends_on:
      - db_person
      - kafka
      # - kafka-setup
    container_name: backendAPIPerson
    build:
      context: backend\ExampleAPI
      dockerfile: ExampleAPI2\Dockerfile
    ports:
      - "7194:80"
    networks:
      - example

  frontend:
    restart: on-failure
    depends_on:
      - backend_address
      - backend_person
    container_name: frontend
    build:
      context: frontend
    ports:
      - "4200:4200"
    networks:
      - example

volumes:
  example_volume:
networks:
  example:
    external: true
