name: BuildAndPublish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test_backend:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./backend/ExampleAPI/ExampleAPI
      
      - name: Build
        run: dotnet build
        working-directory: ./backend/ExampleAPI/ExampleAPI
        
      - name: Test
        run: dotnet test
        working-directory: ./backend/ExampleAPI/TestProject1
        
  build_frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      
      - name: Install Angular
        run: npm install -g @angular/cli
        
      - name: Build
        run: ng build
        working-directory: ./frontend
      
  deploy_backend_to_dockerhub:
    needs: build_and_test_backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./backend/ExampleAPI
        file: ExampleAPI/Dockerfile
        push: true
        
